### ISSUE TITLE
Element class cannot handle empty string. 

### ISSUE THREAD

**Issue by mahmud-islam-mpf** [friskysoft/friskybrowser#10]
i.e. 
The following element results in "No tests found" error: 

`public Element mobileAppListPage = new Element("");`

**Comment by rafaat** [comment]
this is working as designed.
`new Element("")` is an invalid Element selector. The code is preventing the tests to be initiated for empty Element selector.
In order to create placeholder Elements, you should use a dummy CSS or ID instead of empty

**Comment by rafaat** [comment]
Actually, I have decided to allow empty selector with a warning log for now. Will be fixed in next release
